version: "3.7"

networks:

  default-network:
    driver: bridge

services:

  customer-self-service-backend:
    image: lakesidemutual/customer-self-service-backend
    build: customer-self-service-backend
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: eureka
      POLICYMANAGEMENT_TCPBROKERBINDADDRESS: tcp://policy-management-backend:61616
    volumes:
        - maven_repo:/root/.m2
    ports:
      - "8080:8080"

  customer-management-backend:
    image: lakesidemutual/customer-management-backend
    build: customer-management-backend
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: eureka
    volumes:
        - maven_repo:/root/.m2
    ports:
      - "8100:8100"

  policy-management-backend:
      build: policy-management-backend
      image: lakesidemutual/policy-management-backend
      depends_on:
        - customer-core
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE : http://eureka-server:8761/eureka
        SPRING_PROFILES_ACTIVE : eureka
      ports:
        - "8090:8090"
        - "61613:61613"
        - "61616:61616"
      volumes:
        - "maven_repo:/root/.m2"

  customer-core:
    image: lakesidemutual/customer-core
    build: customer-core
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_PROFILES_ACTIVE: eureka
    volumes:
        - maven_repo:/root/.m2
    ports:
      - "8110:8110"

