apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customermanagementcontainer
  name: customermanagementcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementcontainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customermanagementcontainer
    spec:
      containers:
      - image: customermanagementcontainer
        imagePullPolicy: "Never"
        name: customermanagementcontainer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customermanagementcontainer
  name: customermanagementcontainer
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
  selector:
    app: customermanagementcontainer
  type: ClusterIP
status:
  loadBalancer: {}
