apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customercorecontainer
  name: customercorecontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercorecontainer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customercorecontainer
    spec:
      containers:
      - image: customercorecontainer
        imagePullPolicy: "Never"
        name: customercorecontainer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customercorecontainer
  name: customercorecontainer
spec:
  ports:
  - name: "8110"
    port: 8110
    targetPort: 8110
  selector:
    app: customercorecontainer
  type: ClusterIP
status:
  loadBalancer: {}
